{% set name = "hunter" %}
{% set version = "3.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d953a4a8087bb8a6746f06bd6b4dd7c61bc6c60a57012139618fea7aeca2ffe2

build:
  number: 0
  entry_points:
    - hunter-trace = hunter.remote:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - colorama
    - manhole  # [not win]

test:
  imports:
    - hunter
  commands:
    - hunter-trace --help  # [not win]

about:
  home: https://github.com/ionelmc/python-hunter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Hunter is a flexible code tracing toolkit

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
