{% set name = "hunter" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 88a4599aa58a02e8b3c2c48d4a3f690d32ab2876a08aa4721b4c2f47f548c0a7

build:
  number: 0
  entry_points:
    - hunter-trace = hunter.remote:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - colorama
    - manhole  # [not win]

test:
  imports:
    - hunter
  commands:
    - hunter-trace --help  # [not win]

about:
  home: https://github.com/ionelmc/python-hunter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Hunter is a flexible code tracing toolkit

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
